# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doggy < Formula
  desc "Minimal tui (terminal user interface) for docker"
  homepage "https://github.com/pyaillet/doggy"
  url "https://github.com/pyaillet/doggy/archive/refs/tags/v0.4.1.tar.gz"
  sha256 "a54c91da66d41bab952f6ac72ab9371bb856e057205274acd5b32a8031997ddc"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.1/doggy-0.4.1-darwin-amd64.tar.gz"
      sha256 "660921684655e8f3ce89904224577ac397d28e2b97d1e8c9641f9d7a3508ea3a"
    end

    on_arm do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.1/doggy-0.4.1-darwin-arm64.tar.gz"
      sha256 "bde8feb3b73403715aa8a6e45f94bd206f69a2b75b99f49f242b91d65cdd2e60"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.1/doggy-0.4.1-linux-amd64.tar.gz"
      sha256 "90079b0bc1cf09e77b2cec4fa4225c18ecfbac746620b0c08d619d3c4ab7b6e2"
    end

    on_arm do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.1/doggy-0.4.1-linux-arm64.tar.gz"
      sha256 "ab87367d327fbcd784214f240074ab2283afd976af6ac599238f7d9cfe89bf39"
    end
  end

  def install
    'bin.install "doggy" => "doggy"'
  end

  test do
    'assert_match("doggy", shell_output("doggy --version"))'
  end
end
