# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doggy < Formula
  desc "Minimal tui (terminal user interface) for docker"
  homepage "https://github.com/pyaillet/doggy"
  url "https://github.com/pyaillet/doggy/archive/refs/tags/v0.5.1.tar.gz"
  sha256 "b12700ec606d0f85969ec4241b3c26ab9fba64d266bb146ebc9fea4aec860c52"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pyaillet/doggy/releases/download/v0.5.1/doggy-0.5.1-darwin-amd64.tar.gz"
      sha256 "a64dad6d8a32447bce408d5d96a33b83a752687aeb060d7f94f50fa4dd29f272"
    end

    on_arm do
      url "https://github.com/pyaillet/doggy/releases/download/v0.5.1/doggy-0.5.1-darwin-arm64.tar.gz"
      sha256 "bb5d11c909cc6b21524eb3c49e71a079c099bc0b3c381e670bcf9d0ca914eed6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pyaillet/doggy/releases/download/v0.5.1/doggy-0.5.1-linux-amd64.tar.gz"
      sha256 "6351e9713b035198db27308eeb44780a1910696508c4510083dded19c0fb7304"
    end

    on_arm do
      url "https://github.com/pyaillet/doggy/releases/download/v0.5.1/doggy-0.5.1-linux-arm64.tar.gz"
      sha256 "d0a21af44415666c139f258a537bd42bedf25d8681a3118755f29646e99fb482"
    end
  end

  def install
    bin.install "doggy" => "doggy"
  end

  test do
    assert_match("doggy", shell_output("doggy --version"))
  end
end
