# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doggy < Formula
  desc "Minimal tui (terminal user interface) for docker"
  homepage "https://github.com/pyaillet/doggy"
  url "https://github.com/pyaillet/doggy/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "85a64858038d9f9adddb93804b9d6089fb954bd83a980863b4d7a74a5602d98b"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.0/doggy-0.4.0-darwin-amd64.tar.gz"
      sha256 "d7293de4eaa97f4452b78d08e2774356316c2fe220e9356ec4c2f15a82b954e0"
    end

    on_arm do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.0/doggy-0.4.0-darwin-arm64.tar.gz"
      sha256 "e99ee26c36e95e5120a4dddf97fece4ecc099784fc5c1518a11c4fa0f50b0220"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.0/doggy-0.4.0-linux-amd64.tar.gz"
      sha256 "94d774af1aa6f886a4b030c2ba475c945bed2893a3940cf09e1e513c1c58a3dd"
    end

    on_arm do
      url "https://github.com/pyaillet/doggy/releases/download/v0.4.0/doggy-0.4.0-linux-arm64.tar.gz"
      sha256 "561ad3c19ce53c71817ae0bd3ecdeb8d265cba4bc8de2dc2dcf9d7faf8dfcdce"
    end
  end

  def install
    bin.install "doggy" => "doggy"
  end

  test do
    assert_match("doggy", shell_output("doggy --version"))
  end
end
